INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santafé de Bogotá','Santafé de Bogotá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Nariño','Amazonas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Leticia','Amazonas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Medellín','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Abejorral','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Abriaqui','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Alejandría','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Amagá','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Amalfi','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Andes','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Angelópolis','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Angostura','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Anorí','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Antioquia','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Anzá','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Apartadó','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Arboletes','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Argelia','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Armenia','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Barbosa','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Belmira','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bello','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Betania','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Betulia','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bolívar','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Briseño','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Buriticá','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cáceres','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Caicedo','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Caldas','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Campamento','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cañasgordas','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Caracolí','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Caramanta','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Carepa','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Carmen de Viboral','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Carolina','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Caucasia','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chigorodó','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cisneros','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cocorná','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Concepción','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Concordia','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Copacabana','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Dabeiba','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Don Matías','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ebéjico','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Bagre','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Entrerríos','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Envigado','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Fredonia','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Frontino','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Giraldo','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Girardota','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gómez Plata','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Granada','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guadalupe','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guarne','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guatapé','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Heliconia','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Hispania','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Itagüí','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ituango','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Jardín','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Jericó','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Ceja','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Estrella','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Pintada','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Unión','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Liborina','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Maceo','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Marinilla','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Montebello','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Murindó','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mutatá','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nariño','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Necoclí','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nechí','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Olaya','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Peñol','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Peque','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pueblorrico','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Berrío','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Nare','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Triunfo','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Remedios','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Retiro','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Rionegro','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sabanalarga','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sabaneta','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Salgar','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Andrés','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Carlos','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San francisco','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Jerónimo','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San José de Montaña','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Juan de Urabá','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Luis','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Pedro','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Pedro de Urabá','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Rafael','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Roque','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Vicente','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Bárbara','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Rosa de Osos','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santo Domingo','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santuario','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Segovia','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sonsón','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sopetrán','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Támesis','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tarazá','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tarso','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Titiribí','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Toledo','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Turbo','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Uramita','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Urrao','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Valdivia','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Valparaíso','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Vegachí','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Venecia','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Vigía del Fuerte','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Yalí','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Yarumal','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Yolombó','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Yondó (Casabe)','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Zaragoza','Antioquia',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Arauca','Arauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Arauquita','Arauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cravo Norte','Arauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Fortul','Arauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Rondón','Arauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Fortul','Arauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Rondón','Arauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Saravena','Arauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tame','Arauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Barranquilla','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Baranoa','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Campo de la Cruz','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Candelaria','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Galapa','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Juan de Acosta','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Luruaco','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Malambo','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Manatí','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Palmar de Varela','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Piojó','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Polonuevo','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ponedera','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Colombia','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Repelón','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sabanagrande','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sabanalarga','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Lucía','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santo Tomás','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Soledad','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Suán','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tubará','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Usiacurí','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cartagena','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Achí','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Altos del Rosario','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Arenal','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Arjona','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Arroyohondo','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Barranco de Loba','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Calamar','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cantagallo','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cicuto','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Córdoba','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Clemencia','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Carmen de Bolívar','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Guamo','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Peñón','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Hatillo de Loba','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Magangue','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mahates','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Margarita','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'María la Baja','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Montecristo','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mompós','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Morales','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pinillos','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Regidor','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Río Viejo','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Cristóbal','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Estanislao','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Fernando','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Jacinto','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Jacinto del Cauca','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Juan Nepomuceno','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Martín de Loba','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Pablo','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Catalina','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Rosa','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Rosa del Sur','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Simití','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Soplaviento','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Talaigua Nuevo','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tiquisio (Puerto Rico)','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Turbaco','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Turbaná','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villanueva','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Zambrano','Atlantico',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tunja','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Almeida','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Aquitania','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Arcabuco','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Belén','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Berbeo','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Beteitiva','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Boavita','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Boyacá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Briseño','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Buenavista','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Busbanzá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Caldas','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Campohermoso','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cerinza','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chinavita','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chiquinquirá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chiscas','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chita','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chitaranque','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chivatá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ciénaga','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cómbita','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Coper','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Corrales','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Covarachia','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cubar','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cucaita','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cuitiva','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chíquiza','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chivor','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Duitama','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Cocuy','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Espino','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Firavitoba','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Floresta','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gachantivá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gámeza','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Garagoa','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guacamayas','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guateque','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guayatá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guicán','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Iza','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Jenesano','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Jericó','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Labranzagrande','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Capilla','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Victoria','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Ubita','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villa de Leyva','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Macanal','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Maripí','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Miraflores','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mongua','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Monguí','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Moniquirá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Motavita','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Muzo','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nobsa','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nuevo Colón','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Oicatá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Otanche','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pachavita','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Páez','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Paipa','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pajarito','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Panqueba','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pauna','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Paya','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Paz de Río','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pesca','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pisva','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Boyacá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Quípama','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ramiquirí','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ráquira','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Rondón','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Saboyá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sáchica','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Samacá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Eduardo','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San José de Pare','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Luis de Gaceno','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Mateo','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Miguel de Sema','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Pablo de Borbur','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santana','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa María','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Rosa de Viterbo','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Sofía','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sativanorte','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sativasur','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Siachoque','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Soatá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Socotá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Socha','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sogamoso','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Somondoco','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sora','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sotaquirá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Soracá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Susacón','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sutamarchán','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sutatenza','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tasco','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tenza','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tibaná','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tibasosa','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tinjacá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tipacoque','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Toca','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Toguí','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tópaga','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tota','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tunungua','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Turmequé','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tuta','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tutazá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Úmbita','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ventaquemada','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Viracachá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Zetaquirá','Boyacá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Manizales','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Aguadas','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Anserma','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Aranzazu','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Belalcázar','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chinchina','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Filadelfia','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Dorada','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Merced','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Manzanares','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Marmato','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Marquetalia','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Marulanda','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Neira','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pácora','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Palestina','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pensilvania','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Riosucio','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Risaralda','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Salamina','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Samaná','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San José','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Supía','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Victoria','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villamaría','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Viterbo','Caldas',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Florencia','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Albania','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Belén de los Andaquíes','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cartagena del Chairá','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Curillo','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Doncello','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Paujil','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Montañita','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Milán','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Morelia','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Rico','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San José del Fragua','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Vicente del Caguán','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Solano','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Solita','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Valparaíso','Caquetá',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Yopal','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Aguazul','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chameza','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Hato Corozal','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Salina','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Maní','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Monterrey','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nunchía','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Orocué','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Paz de Ariporo','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pore','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Recetor','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sabalarga','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sácama','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Luis de Palenque','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Támara','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tauramena','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Trinidad','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villanueva','Casanare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Popayán','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Almaguer','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Argelia','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Balboa','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bolívar','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Buenos Aires','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cajibío','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Caldono','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Caloto','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Corinto','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Tambo','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Florencia','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guapi','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Inzá','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Jambaló','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Sierra','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Vega','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'López (Micay)','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mercaderes','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Miranda','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Morales','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Padilla','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Páez (Belalcazar)','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Patía (El Bordo)','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Piamonte','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Piendamó','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Tejada','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puracé (Coconuco)','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Rosas','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Sebastián','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santander de Quilichao','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Rosa','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Silvia','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sotará (Paispamba)','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Suárez','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Timbío','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Timbiquí','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Toribío','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Totoro','Cauca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Valledupar','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Aguachica','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Agustín Codazzi','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Astrea','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Becerril','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bosconia','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chimichagua','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chiriguaná','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Curumaní','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Copey','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Paso','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gamarra','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'González','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Gloria','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Jagua de Ibirico','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Manaure Balcón Cesar','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pailitas','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pelaya','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pueblo Bello','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Río de Oro','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Paz (Robles)','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Alberto','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Diego','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Martín','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tamalameque','Cesar',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Montería','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ayapel','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Buenavista','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Canalete','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cereté','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chima','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chinú','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ciénaga de Oro','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cotorra','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Apartada (Frontera)','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Lorica','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Los Córdobas','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Momil','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Montelíbano','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Monitos','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Planeta Rica','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pueblo Nuevo','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Escondido','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Libertador','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Purísima','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sahagún','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Andrés Sotavento','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Antero','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Bernardo del Viento','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Carlos','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Pelayo','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tierralta','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Valencia','Córdoba',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Agua de Dios','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Albán','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Anapoima','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Anolaima','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Arbeláez','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Beltrán','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bituima','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bojacá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cabrera','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cachipay','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cajicá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Caparrapí','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cáqueza','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Carmen de Carupa','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chaguaní','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chía','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chipaque','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Choachí','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chocontá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cogua','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cota','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cucunubá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Colegio','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Peñón','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Rosal','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Facatativá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Fómeque','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Fosca','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Funza','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Fúquene','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Fusagasugá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gachalá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gachancipá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gachetá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gama','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Girardot','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Granada','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guachetá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guaduas','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guasca','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guataquí','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guatavita','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guayabal de Síquima','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guayabetal','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gutiérrez','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Jerusalén','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Junín','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Calera','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Mesa','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Palma','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Peña','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Vega','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Lenguazaque','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Machetá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Madrid','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Manta','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Medina','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mosquera','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nariño','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nemocón','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nilo','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nimaima','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nocaima','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Venecia (Ospina Pérez)','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pacho','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Paime','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pandi','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Paratebueno','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pasca','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Salgar','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pulí','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Quebradanegra','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Quetame','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Quipile','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Rafael','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ricaurte','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Antonio de Tequendama','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Bernardo','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Cayetano','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Francisco','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Juan de Rioseco','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sasaima','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sesquilé','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sibate','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Silvania','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Simijaca','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Soacha','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sopó','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Subachoque','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Suesca','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Supatá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Susa','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sutatausa','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tabio','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tausa','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tena','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tenjo','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tibacuy','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tibiritá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tocaima','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tocancipá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Topaipí','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ubalá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ubaque','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ubaté','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Une','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Útica','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Vergara','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Vianí','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villagómez','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villapinzón','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villeta','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Viotá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Yacopí','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Zipacón','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Zipaquirá','Cundinamarca',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Quibdó','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Acandí','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Alto Baudó (Pie de Pato)','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Atrato (Yuto)','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bagadó','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bahía Solano (Mútis)','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bajo Baudó (Pizarro)','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bojayá (Bellavista)','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cantón de San Pablo','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Condoto','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Carmen','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Litoral de San Juan','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Itsmina','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Juradó','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Lloró','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nóvita','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nuquí','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Riosucio','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San José del Palmar','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sipí','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tadó','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Unguía','Chocó',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Inírida','Guainía',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San José del Guaviare','Guaviare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Calamar','Guaviare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Retorno','Guaviare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Miraflores','Guaviare',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Neiva','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Acevedo','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Agrado','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Aipe','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Algeciras','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Altamira','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Baraya','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Campoalegre','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Colombia','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Elías','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Garzón','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gigante','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guadalupe','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Hobo','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Iquira','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Isnos','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Argentina','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Plata','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Nátaga','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Oporapa','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Paicol','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Palermo','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Palestina','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pital','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pitalito','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Rivera','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Saladoblanco','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Agustín','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa María','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Suazá','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tarqui','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tesalia','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tello','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Teruel','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Timaná','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villavieja','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Yaguará','Huila',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Riohacha','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Barrancas','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Dibulla','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Distracción','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Molino','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Fonseca','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Hatonuevo','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Maicao','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Manaure','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Juan del Cesar','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Uribía','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Urumita','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villanueva','La Guajira',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Marta','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Aracataca','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ariguaní (El Difícil)','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cerro San Antonio','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chivolo','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ciénaga','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Banco','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Piñón','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Retén','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Fundación','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guamal','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pedraza','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pijiño del Carmen','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pivijay','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Plato','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Publoviejo','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Remolino','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Salamina','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Sebastián de Buuenavista','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Zenón','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Ana','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sitionuevo','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tenerife','Magdalena',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villavicencio','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Acacias','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Barranca de Upía','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cabuyaro','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Castilla la Nueva','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cubarral','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cumaral','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Calvario','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Castillo','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Dorado','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Fuente de Oro','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Granada','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guamal','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mapiripán','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mesetas','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Macarena','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Uribe','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Lejanías','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Concordia','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Gaitán','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto López','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Lleras','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Rico','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Restrepo','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Carlos de Guaroa','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Juan de Arama','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Juanito','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Martín','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Vistahermosa','Meta',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pasto','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Albán (San José)','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Aldana','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ancuyá','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Arboleda (Berruecos)','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Barbacoas','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Belén','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Buesaco','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Colón (Génova)','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Consacá','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Contadero','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Córdoba','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cuaspud (Carlosama)','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cumbal','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cumbitará','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chachagüi','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Charco','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Rosario','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Tablón','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Tambo','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Funes','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guachucal','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guaitarilla','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gualmatán','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Iles','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Imúes','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ipiales','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Cruz','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Florida','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Llanada','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Tola','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Unión','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Leiva','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Linares','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Los Andes (Sotomayor)','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Magüí (Payán)','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mallama (Piedrancha)','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mosquera','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Olaya','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ospina','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Francisco Pizarro','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Policarpa','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Potosí','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Providencia','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerres','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pupiales','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ricaurte','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Roberto Payán (San José)','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Samaniego','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sandoná','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Bernardo','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Lorenzo','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Pablo','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Pedro de Cartago','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Bárbara (Iscuandé)','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Cruz (Guachávez)','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sapuyés','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Taminango','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tangua','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tumaco','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Túquerres','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Yacuanquer','Nariño',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cúcuta','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Abrego','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Arboledas','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bochalema','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bucarasica','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cácota','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cáchira','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chinácota','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chitagá','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Convención','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cucutilla','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Durania','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Carmen','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Tarra','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Zulia','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gramalote','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Hacarí','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Herrán','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Labateca','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Esperanza','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Playa','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Los Patios','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Lourdes','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mutiscua','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ocaña','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pamplona','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pamplonita','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Santander','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ragonvalia','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Salazar','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Calixto','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Cayetano','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santiago','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sardinata','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Silos','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Teorama','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tibú','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Toledo','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villacaro','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villa del Rosario','Norte de Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mocoa','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Colón','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Orito','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Asís','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Caicedo','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Guzmán','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Leguízamo','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sibundoy','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Francisco','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Miguel','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santiago','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villa Gamuez (La Hormiga)','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villa Garzón','Putumayo',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Armenia','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Buenavista','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Calarcá','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Circasia','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Córdoba','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Filandia','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Génova','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Tebaida','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Montenegro','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pijao','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Quimbaya','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Salento','Quindío',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pereira','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Apía','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Balboa','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Belén de Umbría','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Dos Quebradas','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guática','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Celia','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Virginia','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Marsella','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mistrató','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pueblo Rico','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Quinchia','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Rosa de Cabal','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santuario','Risaralda',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Andrés','San Andrés',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Providencia','San Andrés',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bucaramanga','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Aguada','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Albania','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Aratoca','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Barbosa','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Barichara','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Barrancabermeja','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Betulia','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bolívar','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cabrera','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'California','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Capitanejo','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Carcasí','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cepitá','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cerrito','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Charalá','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Charta','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chima','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chipatá','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cimitarra','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Concepción','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Confines','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Contratación','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Coromoro','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Curití','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Carmen','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Guacamayo','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Peñón','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Playón','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Encino','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Enciso','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Florián','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Floridablanca','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Galán','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Gámbita','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Girón','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guaca','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guadalupe','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guapotá','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guavata','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guepsa','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Hato','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Jesús María','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Jordán','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Belleza','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Landázuri','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Paz','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Lebrija','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Los Santos','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Macaravita','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Málaga','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Matanza','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mogotes','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Molagavita','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ocamonte','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Oiba','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Onzága','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Palmar','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Palmas del Socorro','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Páramo','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pie de Cuesta','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pinchote','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puente Nacional','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Parra','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Wilches','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Rionegro','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sabana de Torres','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Andrés','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Benito','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Gil','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Joaquín','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San José de Miranda','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Miguel','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Vicente de Chucurí','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Bárbara','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Helena del Opón','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Simacota','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Socorro','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Suaita','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sucre','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Suratá','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tona','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Valle de San José','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Vélez','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Vetas','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villanueva','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Zapatoca','Santander',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sincelejo','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Buenavista','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Caimito','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Coloso (Ricaurte)','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Corozal','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chalán','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Galeras (Nueva Granada)','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guarandá','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Unión','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Los Palmitos','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Majagual','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Morroa','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ovejas','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Palmito','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sampués','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Benito Abad','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Juan de Betulia','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Marcos','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Onofre','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Pedro','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sincé','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sucre','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tolú','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Toluviejo','Sucre',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ibagué','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Alpujarra','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Alvarado','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ambalema','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Anzóategui','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Armero (Guayabal)','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ataco','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cajamarca','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Carmen de Apicalá','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Casabianca','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Chaparral','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Coello','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Coyaima','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cunday','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Dolores','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Espinal','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Falán','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Flandes','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Fresno','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guamo','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Herveo','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Honda','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Icononzo','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Lérida','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Líbano','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mariquita','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Melgar','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Murillo','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Natagaima','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ortega','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Palocabildo','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Piedras','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Planadas','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Prado','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Purificación','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Rioblanco','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Roncesvalles','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Rovira','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Saldaña','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Antonio','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Luis','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Isabel','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Suárez','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Valle de San Juan','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Venadillo','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villahermosa','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Villarrica','Tolima',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cali','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Alcalá','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Andalucía','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ansermanuevo','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Argelia','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bolívar','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Buenaventura','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Buga','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Bugalagrande','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Caicedonia','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Calima (Darién)','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Candelaria','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cartago','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Dagua','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Águila','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Cairo','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Cerrito','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'El Dovio','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Florida','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ginebra','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Guacarí','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Jamundí','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Cumbre','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Unión','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Victoria','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Obando','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Palmira','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Pradera','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Restrepo','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Riofrío','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Roldanillo','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'San Pedro','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Sevilla','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Toro','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Trujillo','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tuluá','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Ulloa','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Versalles','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Vijes','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Yotoco','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Yumbo','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Zarzal','Valle',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Mitú','Vaupés',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Carurú','Vaupés',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Tatamá','Vaupés',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Puerto Carreño','Vichada',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'La Primavera','Vichada',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Santa Rosalia','Vichada',1);
INSERT INTO ciudades(ciudad,departamento,pais_id) VALUES( 'Cumaribo','Vichada',1);
